### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by GLledo** [JMO17/ProyectoIntegra2#4]

**Comment by JMO17** [comment]
[Realizado-Viernes-11-01-2019-ProyectoIntegra2.zip](https://github.com/JMO17/ProyectoIntegra2/files/2750574/Realizado-Viernes-11-01-2019-ProyectoIntegra2.zip)

**Comment by JMO17** [comment]
Subido lo que hemos realizado en clase el dia 11 de Enero del 2019
